[versions]
adjust-android = "5.5.0"
ads-mobile-sdk = "1.2.1"
agp = "8.13.2"
appcompat = "1.7.1"
applovin = "13.5.1.0"
applovin-sdk = "13.5.1"
blurry = "4.0.1"
cardview = "1.0.0"
coil-compose = "2.7.0"
constraintlayout = "2.2.1"
espresso-core = "3.7.0"
facebook = "6.21.0.0"
facebook-login = "18.3.0"
firebase-analytics-ktx = "22.5.0"
firebase-crashlytics = "20.0.4"
firebase-config-ktx = "22.1.2"
firebase-analytics = "23.2.0"
firebase-bom = "34.3.0"
glide = "5.0.5"
infer-annotation = "0.18.0"
inmobi = "11.3.0.1"
installreferrer = "2.2"
ironsource-adapter = "9.2.0.0.0"
junit = "4.13.2"
junit-version = "1.3.0"
json = "20240303"
kotlin = "2.3.0"
kotlin-metadata = "2.3.0"
core-ktx = "1.15.0"
datastore = "1.0.0"
lifecycle = "2.10.0"
activity-compose = "1.9.3"
compose-bom = "2024.12.01"
lifecycle-extensions = "2.2.0"
lifecycle-runtime-ktx = "2.10.0"
lottie = "6.7.1"
mintegral = "17.1.61.0"
multidex = "2.0.1"
navigation-compose = "2.8.5"
hilt = "2.57.1"
hilt-navigation-compose = "1.2.0"
pangle = "8.1.0.5.0"
picasso = "2.71828"
play-services-ads-identifier = "18.2.0"
play-services-appset = "16.1.0"
recyclerview = "1.4.0"
sdp-android = "1.1.1"
shimmer = "0.5.0"
ssp-android = "1.1.1"
lottie-compose = "6.6.2"
google-services = "4.4.4"
android-mail = "1.6.8"
ksp   = "2.3.3"
unity = "4.16.5.0"
unity-ads = "4.16.5"
vungle = "7.6.1.0"
crashlytics-plugin = "3.0.6"
desugar-jdk-libs = "2.1.5"
screenshot = "0.0.1-alpha15"


billingclient = "8.0.0"

[libraries]
# AndroidX & Lifecycle
adjust-android = { module = "com.adjust.sdk:adjust-android", version.ref = "adjust-android" }
adjust-android-webbridge = { module = "com.adjust.sdk:adjust-android-webbridge", version.ref = "adjust-android" }
ads-mobile-sdk = { module = "com.google.android.libraries.ads.mobile.sdk:ads-mobile-sdk", version.ref = "ads-mobile-sdk" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
applovin = { module = "com.google.ads.mediation:applovin", version.ref = "applovin" }
applovin-sdk = { module = "com.applovin:applovin-sdk", version.ref = "applovin-sdk" }
blurry = { module = "jp.wasabeef:blurry", version.ref = "blurry" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junit-version" }
facebook = { module = "com.google.ads.mediation:facebook", version.ref = "facebook" }
facebook-login = { module = "com.facebook.android:facebook-login", version.ref = "facebook-login" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebase-crashlytics" }
firebase-config-ktx = { module = "com.google.firebase:firebase-config-ktx", version.ref = "firebase-config-ktx" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
infer-annotation = { module = "com.facebook.infer.annotation:infer-annotation", version.ref = "infer-annotation" }
inmobi = { module = "com.google.ads.mediation:inmobi", version.ref = "inmobi" }
installreferrer = { module = "com.android.installreferrer:installreferrer", version.ref = "installreferrer" }
ironsource-adapter = { module = "com.applovin.mediation:ironsource-adapter", version.ref = "ironsource-adapter" }
junit = { module = "junit:junit", version.ref = "junit" }
json = { module = "org.json:json", version.ref = "json" }
lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecycle-runtime-ktx" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-extensions" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# Compose
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }

# Navigation
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
mintegral = { module = "com.google.ads.mediation:mintegral", version.ref = "mintegral" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }

# Hilt / DI
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
kotlin-metadata-jvm = { group = "org.jetbrains.kotlin", name = "kotlin-metadata-jvm", version.ref = "kotlin-metadata" }
pangle = { module = "com.google.ads.mediation:pangle", version.ref = "pangle" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
play-services-ads-identifier = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "play-services-ads-identifier" }
play-services-appset = { module = "com.google.android.gms:play-services-appset", version.ref = "play-services-appset" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdp-android" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
ssp-android = { module = "com.intuit.ssp:ssp-android", version.ref = "ssp-android" }

#libs
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie-compose" }
android-activation = { module = "com.sun.mail:android-activation", version.ref = "android-mail" }
android-mail = { module = "com.sun.mail:android-mail", version.ref = "android-mail" }
unity = { module = "com.google.ads.mediation:unity", version.ref = "unity" }
unity-ads = { module = "com.unity3d.ads:unity-ads", version.ref = "unity-ads" }
vungle = { module = "com.google.ads.mediation:vungle", version.ref = "vungle" }

billing = { module = "com.android.billingclient:billing", version.ref = "billingclient" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar-jdk-libs" }
screenshot-validation-api = { group = "com.android.tools.screenshot", name = "screenshot-validation-api", version.ref = "screenshot" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics-plugin" }
screenshot = { id = "com.android.compose.screenshot", version.ref = "screenshot" }
