package com.asianmobile.privatebrower.constant

// Premium
const val PRODUCT_ID = "asian_mobile_photo_file_recovery"
const val BASE_WEEKLY_COST_ID = "photo-file-recovery-weekly-cost"
const val BASE_MONTHLY_COST_ID = "photo-file-recovery-monthly-cost"
const val BASE_YEARLY_COST_ID = "photo-file-recovery-yearly-cost"

// language code
const val EN = "en"
const val ES = "es"
const val FR = "fr"
const val DE = "de"
const val IT = "it"
const val JA = "ja"
const val KO = "ko"
const val ZH = "zh"
const val RU = "ru"
const val PT = "pt"
const val AR = "ar"
const val TR = "tr"
const val VI = "vi"
const val HI = "hi"
const val UR = "ur"
const val MS = "ms"
const val ZU = "zu"
const val HA = "ha"
const val AF = "af"
const val EN_REGION = "us"
const val HA_REGION = "NG"
const val HI_REGION = "IN"
const val VI_REGION = "VN"
const val LANGUAGE_KEY = "language_key"
const val REGION_KEY = "region_key"

