#!/usr/bin/env python3
"""Sync an audited Battery snapshot into app-specific debug storage."""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path


DEFAULT_PACKAGE = "com.asianmobile.emojibattery.shimeji"
REMOTE_DIRECTORIES = {
    "remote/thumbnails": "thumb",
    "remote/batteries": "battery",
    "remote/emojis": "emoji",
    "bundled/assets/background_template": "background",
    "bundled/assets/cute_emotion": "emotion",
}


def _run(command: list[str]) -> None:
    subprocess.run(command, check=True)


def _adb_prefix(serial: str | None) -> list[str]:
    prefix = ["adb"]
    if serial:
        prefix.extend(["-s", serial])
    return prefix


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sync normalized Battery catalog/assets to an installed debug app."
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=Path("private_data/battery-apk-1.0.2/battery-data"),
        help="Captured battery-data directory",
    )
    parser.add_argument(
        "--catalog",
        type=Path,
        default=Path(
            "private_data/battery-apk-1.0.2/battery-runtime/catalog.json"
        ),
        help="Normalized catalog generated by battery_data_snapshot.py",
    )
    parser.add_argument("--package", default=DEFAULT_PACKAGE)
    parser.add_argument("--serial", help="Optional adb device serial")
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    if shutil.which("adb") is None:
        print("adb is not available", file=sys.stderr)
        return 1
    source = args.source.resolve()
    catalog = args.catalog.resolve()
    if not catalog.is_file():
        print(
            "normalized catalog is missing; run tools/battery_data_snapshot.py first",
            file=sys.stderr,
        )
        return 1
    for source_directory in REMOTE_DIRECTORIES:
        if not (source / source_directory).is_dir():
            print(f"missing source directory: {source / source_directory}", file=sys.stderr)
            return 1

    adb = _adb_prefix(args.serial)
    device_root = f"/sdcard/Android/data/{args.package}/files/battery_catalog"
    _run(adb + ["shell", "mkdir", "-p", device_root])
    _run(adb + ["push", str(catalog), f"{device_root}/catalog.json"])
    for source_directory, target_directory in REMOTE_DIRECTORIES.items():
        target = f"{device_root}/{target_directory}"
        _run(adb + ["shell", "mkdir", "-p", target])
        _run(adb + ["push", f"{source / source_directory}/.", f"{target}/"])

    print(f"Battery catalog synced to {device_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
